# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Simon Geard
#
# Generate the foptions.mk file

set c [dict create]

dict set c gfortran {
ODIR     := obj_$(F)_$(BUILD)
MOD_OPTS := -J$(ODIR) -I$(ODIR)
F_BASE   := -cpp -Wall $(F_EXTRA_GF)
ifdef debug
    F_BUILD := -ggdb -fbounds-check -ffpe-trap=denormal,invalid -fPIC
else
    F_BUILD := -O3 -fPIC
endif
F_LOPTS  := -Wl,-z,execstack $(F_LOPTS_GF)
}
    
dict set c ifx {
ODIR     := obj_intel_$(BUILD)
MOD_OPTS := -module $(ODIR) -I$(ODIR)
F_BASE   := -stand f23 -fpp $(F_EXTRA_IFX)
ifdef debug
    F_BUILD := -g -debug-parameters -O0 -check all -warn all -fPIC
else
    F_BUILD := -O3 -fp-model precise -fprotect-parens -xHost -warn all -fPIC
endif
F_LOPTS  := -static-intel -Wl,-z,noexecstack $(F_LOPTS_IFX)
}

dict set c lfortran {
ODIR     := obj_lf_$(BUILD)
MOD_OPTS :=
F_BASE   := --cpp --generate-object-code $(F_EXTRA_LF)
ifdef debug
    F_BUILD := -g
else
    F_BUILD := -O3
endif
F_LOPTS  := $(F_LOPTS_LF)
}

dict set c flang {
ODIR     := obj_flang_$(BUILD)
MOD_OPTS := -J$(ODIR) -I$(ODIR)
F_BASE   := -cpp -DNO_PDT $(F_EXTRA_FL)
ifdef debug
    F_BUILD := -g
else
    F_BUILD := -O3
endif
ifeq ($(shell uname -m),x86_64)
    F_LOPTS  := -L/usr/lib/gcc/x86_64-mageia-linux/12 -B/usr/lib/gcc/x86_64-mageia-linux/12
else
    F_LOPTS  := -L/data/data/com.termux/files/usr/lib/clang/21/lib
endif
F_LOPTS += -Wl,-z,execstack $(F_LOPTS_FL)
}

# =============================================================================

# Check argument
if {$argc != 2} {
    puts "Usage:  $argv0 <ifx|gfortran|lfortran|flang> <output file>"
    exit 1
}
lassign $argv comp ofile
if {! [dict exists $c $comp]} {
    puts "***Error: $comp not supported"
    exit 1
}

set header_mk "

# This makefile built for Fortran compiler = $comp

# foptions.mk - shared Fortran compiler settings
# Include this from a project Makefile after setting any of:
#   F_EXTRA_GF   - extra gfortran flags (appended to F_BASE)
#   F_EXTRA_IFX  - extra ifx flags      (appended to F_BASE)
#   F_EXTRA_LF   - extra lfortran flags (appended to F_BASE)
#   F_EXTRA_FL   - extra flang flags (appended to F_BASE)
#   F_LOPTS_GF   - gfortran link flags
#   F_LOPTS_IFX  - ifx link flags
#   F_LOPTS_LF   - lfortran link flags
#   F_LOPTS_FL   - flang link flags


ifdef debug
  BUILD := debug
  EXT   := _d
else
  BUILD := release
  EXT   :=
endif
"

set footer_mk {
F_OPTS := $(F_BASE) $(F_BUILD) $(MOD_OPTS)
}

set fh [open $ofile w]
puts $fh "\n# Generated by [file tail [info script]] on [clock format [clock seconds]]"
puts $fh $header_mk
puts $fh [dict get $c $comp]
puts $fh $footer_mk
close $fh
puts "$ofile created"

exit 0
