# Generate the foptions.mk file

set foptions_mk {

# foptions.mk - shared Fortran compiler settings
# Include this from a project Makefile after setting any of:
#   F_EXTRA_GF   - extra gfortran flags (appended to F_BASE)
#   F_EXTRA_IFX  - extra ifx flags      (appended to F_BASE)
#   F_EXTRA_LF   - extra lfortran flags (appended to F_BASE)
#   F_LOPTS_GF   - gfortran link flags
#   F_LOPTS_IFX  - ifx link flags
#   F_LOPTS_LF   - lfortran link flags

F ?= gfortran

ifdef debug
  BUILD := debug
  EXT   := _d
else
  BUILD := release
  EXT   :=
endif

ifeq ($(F),ifx)
  ODIR     := obj_intel_$(BUILD)
  MOD_OPTS := -module $(ODIR) -I$(ODIR)
  F_BASE   := -stand f23 -fpp $(F_EXTRA_IFX)
  ifdef debug
    F_BUILD := -g -debug-parameters -O0 -check all -warn all -fPIC
  else
    F_BUILD := -O3 -fp-model precise -fprotect-parens -xHost -warn all -fPIC
  endif
  F_LOPTS  := $(F_LOPTS_IFX)

else

  ifeq ($(F),lf)
    ODIR     := obj_lf_$(BUILD)
    MOD_OPTS :=
    F_BASE   := --cpp --generate-object-code $(F_EXTRA_LF)
    ifdef debug
      F_BUILD := -g
    else
      F_BUILD := -O3
    endif
    F_LOPTS  := $(F_LOPTS_LF)

  else
    ODIR     := obj_$(F)_$(BUILD)
    MOD_OPTS := -J$(ODIR) -I$(ODIR)
    F_BASE   := -cpp -Wall $(F_EXTRA_GF)
    ifdef debug
      F_BUILD := -ggdb -fbounds-check -ffpe-trap=denormal,invalid -fPIC
    else
      F_BUILD := -O3 -fPIC
    endif
    F_LOPTS  := $(F_LOPTS_GF)
  endif

endif

F_OPTS := $(F_BASE) $(F_BUILD) $(MOD_OPTS)

}

set ofile "foptions.mk"
set fh [open $ofile w]
puts $fh "\n# Generated by [file tail [info script]] on [clock format [clock seconds]]"
puts $fh $foptions_mk
close $fh
puts "$ofile created"
exit 0
